```{r knitr_setup, include = FALSE}
frf <- function(...)
    rprojroot::find_root_file(..., criterion = ".editorconfig", path = ".")

knitr::opts_chunk$set(
    cache.path = frf("cache", knitr::opts_knit$get('rmarkdown.pandoc.to'), "/")
)
```

```{r package_bibliography, include = FALSE}
knitr::write_bib(
    c(
        "base",
        "consort",
        "glmnet",
        "gtsummary",
        "survival",
        "survminer"
    ),
    file = frf("bibliography", "rpackages.bib")
)
```

```{r libraries, include = FALSE}
library("cli")
library("gtsummary")
library("survival")
library("survminer")
```

```{r definitions, include = FALSE}
## manufacturer's colors
mcol <- c(
    Arrow = "#115dce",
    Braun = "#108f34",
    Vygon = "#8f061a"
)
## lumen's lty; survplot just supports integer values
llty <- c(
    "3 Lumens" = 3L, # == "dotted",
    "4 Lumens" = 4L, # == "dotdash",
    "5 Lumens" = 1L  # == "solid"
)

## days of interest
times <- c(1, 3, 5, 7, 9, 11, 13)
```

```{r import, include = FALSE}
cvc <- read.csv(frf("data", "extdata", "cvc.csv"), na.strings = c("NA", ""))
```

```{r abbreviations, include = FALSE}
## labels where the column names are identical to the abbreviation
abbr <- c(
    BMI = "body mass index",
    CLABSI = "central line associated bloodstream infection",
    CRP = "C-related peptide",
    CRT = "catheters-related thrombosis",
    CVC = "central venous catheters",
    DOAC = "direct oral anticoagulation",
    DVT = "deep vein thrombosis",
    FV = "femoral vein",
    ICU = "intensive care unit",
    IQR = "inter-quartile range",
    IJV = "internal jugular vein",
    LMWH = "low molecular weight heparin",
    OR = "operating room",
    PE = "pulmonary embolism",
    Q1 = "first quartile",
    Q3 = "third quartile",
    SCV = "subclavian vein",
    UFH = "unfractionated heparin",
    VTE = "venous thrombotic embolism",
    WBC = "white blood cell counts"
)
```

```{r conversion, include = FALSE}
cvc$FirstExam <- as.numeric(cvc$FirstExam)

fcts <- c(
    "Sex", "Manufacturer", "Site", "Side", "External", "Incision",
    "PerioperativePlacement", "Specialty", "AdmissionType",
    "DVT", "DVT.CVC", "Sepsis", "Cancer", "Smoking",
    "AnticoagulationGroup", "Complications"
)
cvc[fcts] <- lapply(cvc[fcts], as.factor)

cvc$Attempts2 <- factor(
    ifelse(
        is.na(cvc$Attempts), NA, ifelse(cvc$Attempts > 1, ">1", "1")
    ), levels = c("1", ">1")
)

cvc$Experience <- factor(
    cvc$Experience,
    levels = c("<25", "25-50", ">50"),
    ordered = TRUE
)

cvc$ManLu <- factor(paste0(cvc$Manufacturer, cvc$Lumens))

cvc$Side <- relevel(cvc$Side, ref = "right")
cvc$AdmissionType <- relevel(cvc$AdmissionType, ref = "surgical")
cvc$AnticoagulationGroup <- relevel(cvc$AnticoagulationGroup, ref = "LMWH")
cvc$Complications <- relevel(cvc$Complications, ref = "None")
```

```{r exclusion, include = FALSE}
cvc$ExclusionReason[cvc$Site != "IJV"] <-
    paste("Site:", as.character(cvc$Site[cvc$Site != "IJV"]))
cvc$isExcluded <- !is.na(cvc$ExclusionReason)

cvc$ExclusionReason[cvc$External == "yes" & !cvc$isExcluded] <-
    paste("Not inserted in-house")
cvc$isExcluded <- !is.na(cvc$ExclusionReason)

nManLu <- table(cvc$ManLu)
isLowN <- cvc$ManLu %in% names(nManLu)[nManLu < 5] & !cvc$isExcluded
cvc$ExclusionReason[isLowN] <-
    paste0("Lumen: ", cvc$Lumens[isLowN], ", ", cvc$Manufacturer[isLowN])
cvc$ExclusionReason[cvc$ManLu == "Arrow5" & grepl("Arrowg\\+ard", cvc$Type)] <-
    "Lumen: 5, Arrow"
cvc$ExclusionReason[cvc$ManLu == "Vygon5" & grepl("expert", cvc$Type)] <-
    "Lumen: 5, Vygon multicath expert"
cvc$isExcluded <- !is.na(cvc$ExclusionReason)

cvc$ExclusionReason[cvc$AnticoagulationGroup == "DOAC" & !cvc$isExcluded] <-
    "Anticoagulation: DOAC"
cvc$isExcluded <- !is.na(cvc$ExclusionReason)

cvc$ExclusionReason[is.na(cvc$LOT) & !cvc$isExcluded] <-
    "Missing LOT"
cvc$isExcluded <- !is.na(cvc$ExclusionReason)

cvc$ExclusionReason[duplicated(cvc$CaseId)] <-
    "Not the first CVC"
cvc$isExcluded <- !is.na(cvc$ExclusionReason)
```

```{r helper, include = FALSE}
.followup <- function(x)ifelse(x$CRT, x$CRTday, x$FollowUp)
.model <- function(x) {
    x <- droplevels(x[!x$isExcluded,])
    x$CRT <- x$CRT == "CRT"
    x$FUP <- .followup(x)

    svf <- survfit(Surv(FUP, CRT) ~ ManLu, data = x)
    svd <- survdiff(Surv(FUP, CRT) ~ ManLu, data = x, rho = 1)

    list(data = x, svf = svf, svd = svd)
}

#' @param svf survfit object
#' @param times numeric, times to evaluate
.survsummary <- function(svf, times, type = c("surv", "n.event", "n.risk")) {
    type <- match.arg(type, several.ok = TRUE)
    ntype <- length(type)

    ntimes <- length(times)
    nlvls <- length(svf$strata)
    sm <- summary(svf, times = times, extend = TRUE)

    a <- array(
        data = NA_real_,
        dim = c(ntimes, nlvls, ntype),
        dimnames = list(times, names(svf$strata), type)
    )
    a[, , ] <- unlist(sm[type])
    a
}

.nrisk <- function(svf, times = c(1, 3, 5, 7, 9, 11, 13)) {
    apply(.survsummary(svf, times, type = "n.risk"), 2, identity)
}

.survival <- function(svf, times = c(1, 3, 5, 7, 9, 11, 13)) {
    apply(.survsummary(svf, times, type = "surv"), 2, identity)
}

.ncumevents <- function(svf, times = c(1, 3, 5, 7, 9, 11, 13)) {
    a <- .survsummary(svf, times, type = "n.event")
    apply(a, 2, cumsum)
}

.medLU <- function(x, prec=".1") {
    q <- quantile(
        x, probs = c(0.5, 0.25, 0.75), na.rm = TRUE, conf.int = FALSE
    )
    sprintf(
        paste0("%", prec, "f (%", prec, "f, %", prec, "f)"),
        q[1], q[2], q[3]
    )
}

.medCI <- function(x, prec=".1") {
    q <- quantile(
        x, probs = 0.5, na.rm = TRUE, conf.int = TRUE
    )
    sprintf(
        paste0("%", prec, "f (%", prec, "f-%", prec, "f)"),
        q$quantile, q$lower, q$upper
    )
}

.pct <- function(x, prec=".1") {
    sprintf(
        paste0("%", prec, "f%%"), x * 100
    )
}

.tbl1 <- function(variable, column = "Overall", ...) {
    if (column == "Overall")
        column <- "stat_0"
    gtsummary::inline_text(
        tbl1,
        variable = all_of(variable), column = all_of(column), ...
    )
}

.cli_text <- function(...)cli_format_method(cli_text(...))

#' return numbers as words
.as.word <- function(x) {
    ifelse(
        x > 12, x,
        c("one", "two", "three", "four", "five", "six", "seven", "eight",
          "nine", "ten", "eleven", "twelve")[x]
    )
}
.as.Word <- function(x) {
    .toupper.first(.as.word(x))
}
.toupper.first <- function(x) {
    paste0(toupper(substring(x, 1, 1)), substring(x, 2))
}
```

```{r model, include = FALSE}
m <- .model(cvc)
```

```{r stratified, include = FALSE}
m$svd.strata.cancer <-
    survdiff(Surv(FUP, CRT) ~ ManLu + strata(Cancer), data = m$data)
m$svd.strata.sex <-
    survdiff(Surv(FUP, CRT) ~ ManLu + strata(Sex), data = m$data)
```

```{r alternativemodels, include = FALSE}
m.a5v5 <- .model(cvc[cvc$ManLu %in% c("Arrow5", "Vygon5"),])
m.a4a5 <- .model(cvc[cvc$ManLu %in% c("Arrow4", "Arrow5"),])
```

```{r regression, include = FALSE}
rd <- droplevels(m$data)
rd$WBC1 <- log(rd$WBC1)
rd$CRP1 <- log(rd$CRP1)
rd$DDimer1 <- log(rd$DDimer1 + 1)

## complete cases
rgcx <- coxph(
    Surv(FUP, CRT) ~
        Sex + Age + ManLu + Side + AdmissionType + PerioperativePlacement +
        Sepsis + Cancer + DVT + AnticoagulationGroup + WBC1,
    data = rd
)
rgcx.nms <- setNames(names(rgcx$xlevels), names(rgcx$xlevels))
rgcx.nms["ManLu"] <- "CVC Type"
rgcx.nms["PerioperativePlacement"] <- "Perioperative placement"
rgcx.nms["AnticoagulationGroup"] <- "Anticoagulation"
rgcx.nms["AdmissionType"] <- "Admission type"

rd$Experience <- factor(rd$Experience, ordered = FALSE)
rd.na <- na.omit(rd[c(
    "FUP", "CRT", "Sex", "Age", "BMI", "ManLu", "Side",
    "AdmissionType", "PerioperativePlacement",
    "Incision", "Attempts2", "Experience",
    "Specialty", "Sepsis", "Cancer", "DVT", "AnticoagulationGroup",
    "WBC1", "DDimer1", "CRP1")]
)

## all variables (reduced N, due to NA)
rgcx.full <- coxph(Surv(FUP, CRT) ~ ., data = rd.na)

## keep missing LOTs
cvc.lots <- cvc
cvc.lots$isExcluded[cvc$ExclusionReason == "Missing LOT"] <- FALSE
rd.lots = droplevels(.model(cvc.lots)$data)
rgcx.lots <- coxph(
    Surv(FUP, CRT) ~
        Sex + Age + ManLu + Side + AdmissionType + PerioperativePlacement +
        Sepsis + Cancer + DVT + AnticoagulationGroup + WBC1,
    data = rd.lots
)
```

```{r tbl1, include = FALSE}
.manlu2txt <- function(x)paste0(
    substring(x, 1, 5), "/", substring(x, 6, 6), " Lumens"
)

tbl1 <- m$data |>
    dplyr::mutate(
        CRT = factor(
            CRT,
            levels = c(TRUE, FALSE),
            labels = c("CRT", "CRT-free")
        ),
        ManLu = factor(
            ManLu,
            levels = levels(.data$ManLu),
            labels = .manlu2txt(levels(.data$ManLu))
        ),
        AdmissionType = factor(
            AdmissionType,
            levels = levels(.data$AdmissionType),
            labels = .toupper.first(levels(.data$AdmissionType))
        ),
        Complications = factor(
            Complications,
            levels = levels(.data$Complications),
            labels = .toupper.first(levels(.data$Complications))
        )
    ) |>
    select(
        CRT,
        Sex,
        Age,
        BMI,
        ManLu,
        Side,
        Incision,
        Attempts2,
        Experience,
        PerioperativePlacement,
        FirstExam,
        AdmissionType,
        Sepsis,
        Cancer,
        DVT,
        AnticoagulationGroup,
        Complications,
        WBC1,
        CRP1,
        DDimer1
    ) |>
    tbl_summary(
        by = CRT,
        missing_text = "(Missing)",
        type = list(
            Sex ~ "dichotomous",
            DVT ~ "dichotomous",
            Side ~ "dichotomous",
            Attempts2 ~ "dichotomous",
            AnticoagulationGroup ~ "categorical"
        ),
        label = list(
            FirstExam ~ "Time to first exam [hours]",
            Sex ~ "Sex (male)",
            ManLu ~ "Type (Manufacturer/Lumens)",
            DVT ~ "History of vein thrombosis",
            Side ~ "Side of insertion (left)",
            Experience ~ "Experience (number of CVCs in the past)",
            Attempts2 ~ "More than one insertion attempt",
            AdmissionType ~ "Admission type",
            PerioperativePlacement ~ "Placement in the OR",
            AnticoagulationGroup ~ "Type of anticoagulation drug",
            WBC1 ~ "WBC day 1 [Gpt/L]",
            DDimer1 ~ "D-dimer day 1 [mg/L]",
            CRP1 ~ "CRP day 1 [mg/L]"
        ),
        value = list(
            Sex ~ "male",
            DVT ~ "yes",
            Side ~ "left",
            Attempts2 ~ ">1",
            Incision ~ "yes"
        )
    ) |>
    add_overall() |>
    modify_footnote(all_stat_cols() ~ "n (%), Median (Q1, Q3)")

uvar <- unique(c(tbl1$table_body$variable, tbl1$table_body$label))
.abbr <- sort(c(Filter(nchar, abbr[uvar]), abbr[c("CRT", "OR")]))

tbl1 <- tbl1 |>
    modify_caption(
    paste0(
        "Baseline characteristics of all analysed central venous catheters ",
        "in the internal jugular vein.<br /> ",
        "Values are given as ",
        "median (lower quartile (Q1), upper quartile (Q2)) or n (percent).",
        "<br /> ",
        paste(names(.abbr), .abbr, sep = ", ", collapse = "; "), "."
    )
)

tbl1 <- tbl1 |>
    remove_row_type(Complications, type = "level", "None") |>
    remove_row_type(AnticoagulationGroup, type = "level", "None")

```

```{r tablesurv, include = FALSE, message = FALSE, warning = FALSE}
tblsrv <-
    list(
        Overall = survfit(Surv(FUP, CRT) ~ 1, data = m$data),
        ManLu = survfit(
            Surv(FUP, CRT) ~ ManLu,
            data = m$data |> dplyr::mutate(
                ManLu = factor(
                    ManLu,
                    levels = levels(.data$ManLu),
                    labels = .manlu2txt(levels(.data$ManLu))
                )
            )
        )
    ) |>
    tbl_survfit(
        probs = 0.5,
        label = list(
            ManLu ~ "Type (Manufacturer/Lumens)"
        ),
        label_header = "**Median CRT-free time**"
    ) |>
    modify_caption(
    paste0(
        "Median CRT-free time for all central venous catheters ",
        "in the internal jugular vein and for their different types.<br /> ",
        "Values are given as median (lower quartile - upper quartile).<br /> ",
        paste("CRT, ", .abbr["CRT"]), "."
    )
)
```
