# Discussion

In this prospective observational study,
we found asymptomatic CRTs in `r sum(cvc$CRT[!cvc$isExcluded] == "CRT")` of `r sum(!cvc$isExcluded)` CVCs (`r .pct(mean(cvc$CRT[!cvc$isExcluded] == "CRT"))`) in the IVJ of critically ill, mostly surgical patients.
This incidence of CRT is much higher than previous reported 28 to 56% for IVJ CVCs in general surgical ICU or cardiac surgical patients [@Malinoski2013; @Timsit1998; @Wu1999].
To our knowledge, the time of thrombosis onset has not previously studied in surgical patients.
The median (IQR) time from CVC insertion to CRT diagnosis for all CVCs was `r .medLU(survfit(Surv(FUP, CRT) ~ 1, data = m$data), prec = ".0")` days which is comparable to the previously reported 4 (2, 7) days
for CRT onset in medical critically ill patients [@Wu2023].
While in medical critically ill patients the CRT develops slowly and just 12% of CRTs were seen on day one, we have found, depending on the type of CVC, a CRT in up to `r .pct(1 - min(.survsummary(m$svf, times = 1, type = "surv")))` CVCs of surgical critically ill patients within the first 24 hours.
That highlights the importance to check the indication for a CVC critically in the first place, scrutinize it on a daily basis and remove the CVC as early as possible.

Depending on the type of CVC the median time to CRT
varies from `r paste0(.as.word(range(median(m$svf))), c(" day for Arrow4 and Vygon5", " days for Arrow5 and Braun3"), collapse = " to ")`.
Due to differences in manufacturer and material causes are difficult to discuss.
Previously, different incidences of PE due to CRT have been reported in patients with
polyvinyle chloride or polyvinyle catheters compared to those with
polyurethane or siliconized catheters, favouring the latter [@Monreal1994].
We studied two different types of ARROW CVCs, the classic polyurethane and the
chlorhexidine acetate and silver sulfadiazine coated polyurethane ARROWgard Blue (1st generation) catheters.
Others have reported a lower CRT rate with a chlorhexidine gluconate gel dressing alone [@Yamashita2020].
In contrast we have seen a higher CRT rate with the chlorhexidine acetate coated CVCs.
While chlorhexidine should reduce CLABSI it may result in more CRT, which is itself a major risk factor for CLABSI.

Most CRT has been directly associated with vascular endothelial injury.
We assume that the major factors of the Virchow's triad of thrombosis for CRT development are the initial endothelian trauma and the hypercoagulability due to perioperative stress and the inflammation state.
Venous stasis due to obstruction, catheter-to-vessel ratio and volume status may play an inferior role in the first days but may be more important in the long term.
These could explain the higher incidence and faster onset in comparison to medical patients in other studies.

The guideline "antithrombotic therapy for venous thrombotic embolism (VTE)" of the American College of Chest Physicians defines an extensive VTE with a diameter of more than 7 mm and a length of more than 50 mm [@Kearon2012].
Using these thresholds our CRTs were small.
None of our CRTs were longer than 50 mm and just `r .pct(mean(cvc$HeightMax[!cvc$isExcluded] > 7, na.rm = TRUE))` had a maximal height larger than 7 mm.
Because of the irregular, non-circular shape of the CRT, which is often attached on one side of the CVC the largest height is not necessarily identical to the diameter.
In comparison to medical critical ill patients the CRTs were of similar size with a higher rate of thicker CRTs (30% above 7 mm) and none longer than 50 mm [@Wu2023].

While the size of CRT and its progression was neither our primary nor secondary outcome and we didn't measure the size every day if it was not obviously different to the already recorded image most CRT where stable in size.
This is in line with results previously reported [@Wu2023].

Despite the high incidence of CRT we didn't observe any negative outcome.
Based on this observation we can confirm the recommendation of the guidelines to leave the catheter in place [@Kearon2012].
A removal due to the CRT and reinsertion of a new CVC is not necessary and not recommended [@Kearon2012; @Geerts2014].
However the need to treat an asymptomatic, accidentally found CRT with therapeutic anticoagulation has to be questioned.

On the other hand prophylactic anticoagulation at the time of catheter placement seems to be associated with a lower CRT rate.
Especially in patients with cancer prophylactic anticoagulation could reduce CRT [@Kahale2018].
Interestingly this could not be found in some previous studies [@Malinoski2013; @Leung2016; @Wu2023].
However, as mentioned before all of our and most of the reported CRTs are asymptomatic [@Wu1999; @Malinoski2013; @Leung2016; @Wu2023].
That's why the application of prophylactic or therapeutic anticoagulation should balanced against the potential harm of major bleeding and other risks of anticoagulation [@Kahale2018].

## Limitations

Because this was a pragmatical prospective observational trial and we were limited due
to supply shortage the number of catheters per type and manufacturer are very different.
The missing randomisation could yield biased results.
We had to exclude more than the half of all CVCs due to poorly accessiblity by ultrasound, missing LOT information or small number of catheter types.
If we assign the CVCs with missing LOT information to the major type of each manufacturer the sample size increases from `r sum(!cvc$isExcluded)` to `r rgcx.lots$n` and we get very similar results (see supplement \@ref(tab:supplhrtablelots)).
Depending on the vessel the sensitivity and specifity of ultrasound for diagnosing a DVT vary from 87-94% and 85-97%, respectively.
However serial ultrasound assessments as done in our study increase both sensitivity and specifity up to 97.9% and 99.8% [@Patel2020; @Bhatt2020].
Nevertheless the true accuraccy of ultrasound in diagnosis of CRT in the IVJ is not known.

Although we focused on the IVJ our ultrasound based accessment was limited to the proximal part of the CVC and may result in an underestimation in the incidence of CRT.

If the patient was discharged from the ICU we stopped the ultrasound examination which may be another reason for a potential underestimation of the CRT incidence.

Cancer is a well know risk factor for CRT [@Geerts2014; @Kahale2018; @Haggstrom2020].
However cancer includes different types of malignancies but due to our relative small sample size we could not do any subgroup analysis on the type of cancer.
We did not record the type and duration of the surgery which may have an influence on the incidence of CRT as well.

Due to missing information our study is underpowered to give a conclusion on the effect of multiple insertion attempts and the experience of the operator.
However in the reduced sample size we not seen any difference (see supplement) which is in line with previous studies that have shown that the number of insertion attempts and experience of the operator may be unrelated to CRT [@Timsit1998; @Leung2016].
