# Results

## Baseline characteristics

During the six-month study period `r nrow(cvc)` CVCs from
`r sum(!duplicated(cvc$CaseId))` consecutive critically ill patients
were eligible for inclusion.

`r sum(cvc$isExcluded)` CVCs were excluded (see CONSORT flow chart for details: \@ref(fig:consort-flowchart)).
Initially, we decided to include only the first CVC of each patient and excluded `r sum(cvc$ExclusionReason == "Not the first CVC", na.rm = TRUE)` consecutive CVCs.
As catheter entry into the femoral or the subclavian vein was often difficult to visualize with ultrasound,
we focused on the internal jugular vein (IVJ) and excluded  `r sum(cvc$ExclusionReason == "Site: FV", na.rm = TRUE)` and `r sum(cvc$ExclusionReason == "Site: SCV", na.rm = TRUE)` CVCs, respectively.
In addition, we had to exclude a total of `r .as.word(length(grep("Lumen", cvc$ExclusionReason)) + sum(cvc$ExclusionReason == "Not inserted in-house", na.rm = TRUE))` CVCs because of the very small number of catheters of this type (e.g. `r ncvc <- .as.word(sum(cvc$ManLu == "Arrow5" & grepl("ARROWgard", cvc$Type))); .cli_text("{ncvc} CVC{?s}")` by Arrow, 5 lumens with ARROWgard Blue (1st generation) coating) or because they were inserted in an external hospital and we were unable to verify the time of insertion.
As direct oral anticoagulants (DOACs) are an inhomogeneous group and uncommon in our ICU,
we examined only `r s <- length(grep("DOAC", cvc$ExclusionReason)); .cli_text("{(.as.word(s))} {qty(s)}patient{?s} with {qty(s)}{?a/different} {qty(s)}DOAC{?s} and decided to exclude {qty(s)}{?this/these} {qty(s)}CVC{?s}")` as well.
We also had to exclude `r sum(cvc$ExclusionReason == "Missing LOT", na.rm = TRUE)` CVCs due to missing or unreadable LOT information.
Finally, we retained  `r sum(!cvc$isExcluded)` first-time CVCs and patients for our analysis (see Table 1 \@ref(tab:table1)).

`r s <- sort(table(m$data$ManLu), decreasing = TRUE); s <- paste(.as.word(s), names(s)); .cli_text("{ {s}}")` CVCs were used.
Most of them were placed in the right IJV (`r r <- m$data$Side == "right"; sprintf("%i (%s)", sum(r), gtsummary::style_percent(mean(r), symbol = TRUE))`).
A skin incision was made prior to CVC insertion in just over half of the cases.
Two thirds of all CVCs were inserted by experienced practitioners who had inserted more than 50 CVCs.
About the same number of CVCs were placed in the ICU and outside the operating room.
We examined the catheters by ultrasound `r .tbl1("FirstExam")` hours after insertion.

About 80% of the patients admitted to our ICU had previously undergone surgery.
One third had sepsis and about 40% had cancer.
Only `r .tbl1("DVT")` patients had a history of venous thrombosis.

Patients received prophylactic anticoagulation with low-molecular-weighted heparins in two thirds of cases, and unfractionated heparin in only a few.
However, almost a third had no anti-thrombotic prophylaxis at the time of CVC placement.

In general, the patients had an elevated WBC (median (IQR): `r .tbl1("WBC1")`, [Gpt/L]), CRP (`r .tbl1("CRP1")`, [mg/L]), and D-dimer (`r .tbl1("DDimer1")`, [mg/L]) on the first day after CVC insertion.

## Analysis of CRT-free time

The median CRT-free time to the first diagnosed CRT was one day for Arrow4, Braun3 and Vygon5.
Arrow3 and Arrow5 had longer median CRT-free periods of `r .as.word(median(m$svf["ManLu=Arrow3"]))` and `r .as.word(median(m$svf["ManLu=Arrow5"]))` days, respectively (see Table \@ref(tab:tablemedsurv) for details).
Due to catheter removal or discharge from the ICU, we were only able to perform follow-up ultrasound examinations for `r .tbl1("FollowUp")` days.

Specifically, we found CRTs in `r crt <- sort(1 - .survival(m$svf, times = 1)); crt <- paste0(round(crt * 100), "% of all ", sub("^ManLu=", "", names(crt))); .cli_text("{ {crt}}")` CVCs at first examination (within 24 hours; see also Figure \@ref(fig:survplot)).
Within one week of catheterization `r paste0(range(round((1 - .survival(m$svf, times = 7)) * 100)), collapse = " to ")`% of CVCs developed a CRT.

The height and length of the thrombosis remained largely constant over time.
On day one, the median (IQR) height and length were `r .medLU(m$data$Height1)` mm and `r .medLU(m$data$Width1)` mm, respectively.
However, the median (IQR) largest dimension of the thrombosis was almost identical across all examinations: `r .medLU(m$data$HeightMax)` mm and `r .medLU(m$data$WidthMax)` mm (see Supplement  \@ref(fig:crtheightbp) to \@ref(fig:crtwidthovertime) for detailed figures).

A statistical comparison between the CVC type with the lowest CRT rate, Arrow5, and those with the highest CRT rate, gives an unadjusted $p$-value of `r round(m.a4a5$svd$pvalue, 2)` for Arrow4 and `r round(m.a5v5$svd$pvalue, 2)` for Vygon5.
Adjusting the $p$-values for all `r ncmb <- ncol(combn(nlevels(m$data$ManLu), 2)); .as.word(ncmb)` possible comparisons of CVC types gives a $p$-value of
`r round(p.adjust(m.a4a5$svd$pvalue, method = "BH", n = ncmb), 2)` for Arrow4 and `r round(p.adjust(m.a5v5$svd$pvalue, method = "BH", n = ncmb), 2)` for Vygon5 (see the Supplement  for survival plots of these comparisons).

## Complications

Despite the high CRT rate none of the patients had a PE or CLABSI.
However, `r s <- sum(m$data$Complications == "symptomatic thrombosis", na.rm = TRUE); .cli_text("{(.as.word(s))} symptomatic {qty(s)}thrombos{?is/es} {qty(s)}{?was/were}")` observed
and `r s <- sum(m$data$Complications == "removal, suspected infection", na.rm = TRUE); .cli_text("{(.as.word(s))} {qty(s)}CVC{?s} {qty(s)}{?was/were} removed")` because of suspected infection.
`r s <- sum(m$data$Complications == "closed lumen", na.rm = TRUE); .cli_text("{(.as.Word(s))} {qty(s)}CVC{?s} {qty(s)}{?was/were}")` reported to have occluded lumens.

## Analysis of CRT risk factors

In addition to the univariate analyses we applied multiple regression analyses to determine the impact of different variables (see Figure \@ref(fig:forestplot)).
We omitted all variables with missing values in order to maintain the sample size.
However, the results don't vary much even when all variables are included (see Supplement for a regression with half the number of samples but all the variables).

As shown in the forest plot (see Figure \ref(fig:forestplot), the CVC types Arrow4 and Vygon5 were significantly associated with higher rates of CRT.
Their hazard ratios were `r format(exp(rgcx$coefficients["ManLuArrow4"]), digits = 2)` and `r format(exp(rgcx$coefficients["ManLuVygon5"]), digits = 2)`, respectively.
In addition to CVC type, no prophylactic anticoagulation prior to CVC placement was another significant risk factor associated with CRT, with a hazard ratio of `r format(exp(rgcx$coefficients["AnticoagulationGroupNone"]), digits = 2)`.
Furthermore, cancer was also significantly associated with CRT (hazard ratio `r format(exp(rgcx$coefficients["AnticoagulationGroupNone"]), digits = 2)`), but is an inhomogeneous category of disease.
In our cases, cancer was always diagnosed before the CVC insertion.
Nevertheless,  we didn't stratify our regression model for cancer because the chi-square values for the (un)stratified models were very similar
(`r paste(round(c(m$svd$chisq, m$svd.strata.cancer$chisq), 1), collapse = " vs ")`).
Although sex was not a significant risk factor, we tested and rejected stratification for sex for the same reason
(`r paste(round(c(m$svd$chisq, m$svd.strata.sex$chisq), 1), collapse = " vs ")`).
Neither age, side, sepsis, previous deep vein thrombosis (DVT), nor WBC day one were associated with a higher rate of CRT.
Because it is very unlikely that any of the covariates studied, except for laboratory measurements, would change over the short observation period, we didn't look for any time-dependence.
