# Acknowledgement

We thank Katrin Singer (Teleflex/Arrow), Androniki Graf (B. Braun), Johannes Haga Jäger (B. Braun), Silvia Metz (B. Braun), Stephan Schopka (B. Braun) and Tobias Neels (Vygon) for information about the material and properties of the CVCs.
We would also thank Marcus Vollmer for helpful discussions on survival analysis and for proofreading the manuscript.

## Author Contributions

Conceptualization, S.G. and S.K.;
data acquisition, S.E;
data analysis, S.G.;
writing - draft preparation, S.G.;
writing - review and editing, S.E., S.K. and S.G.;
All authors have read and agreed to the published version of the manuscript.

## Competing interests

All authors state no conflict of interest.

## Ethical approval

Research involving human subjects complied with all relevant national regulations and institutional policies, as well as the tenets of the Helsinki Declaration (as revised in 2013), and was approved by the Ethics Committee at the University Medicine Greifswald (reference number: BB 006/22).

## Data and software availability

The complete data, code and reproducible analysis can be found at
https://github.com/umg-minai/crt.
