# Figures

```{r consort-flowchart, echo = FALSE, fig.cap = "The flowchart depicts the inclusion and exclusion criteria. CVC, central venous catheter; FV, femoral vene; SCV, subclavian vene."}
tbl_excl <- table(cvc$ExclusionReason)
nfc <- grepl("Not the first", names(tbl_excl))
tbl_excl <- c(tbl_excl[!nfc], tbl_excl[nfc])
excl_str <- paste0(names(tbl_excl), " (n=", tbl_excl, ")")
graph <- "
digraph flowchart
{
    layout=dot
    labelloc = 't'
    graph [splines='ortho']

    node [shape = box, style = 'rounded,filled', width = 2, height = 0.5, fillcolor = '#7589af'];
    Enrollment [label = 'Enrollment']
    Allocation [label = 'Allocation']
    Analysis [label = 'Analysis']

    edge [weight=1000]

    Enrollment -> Allocation -> Analysis [style = invis]

    node [shape = box, style = rectangle, width = 2, height = 0.5];
    All [label = 'Screened CVCs\\n(n = @@1-1)']
    Excl [label = 'Excluded (n = @@2-1):\\l- @@2-2\\l- @@2-3\\l- @@2-4\\l- @@2-5\\l- @@2-6'];
    CVC [label = 'Eligible CVCs\\n(n = @@3-1)']
    C3VC [label = '3 Lumen CVCs\\n(n = @@4-1)']
    C3VCA [label = '3 Lumen CVCs\\nArrow\\n(n = @@4-1)']
    C3VCB [label = '3 Lumen CVCs\\nBraun\\n(n = @@4-2)']
    C5VC [label = '5 Lumen CVCs\\n(n = @@5-1)']
    C5VCA [label = '5 Lumen CVCs\\nArrow\\n(n = @@5-1)']
    C5VCV [label = '5 Lumen CVCs\\nVygon\\n(n = @@5-2)']

    node [shape = point, width = 0, height = 0, style = invis];
    pAllo;
    pCVC;
    pC3VC;
    pC5VC;

    node [shape = box, style = invis, width = 2, height = 0.5];
    iC35VCa;
    iC35VCb;
    iC3VC;
    iC5VC;

    {rank = same; Enrollment -> All [minlen=23, style = invis]; rankdir = LR;};
    {rank = same; Allocation -> CVC [minlen=23, style = invis]; rankdir = LR;};
    {rank = same; C3VC -> iC35VCa -> iC35VCb -> C5VC [style = invis]; rankdir = LR;};

    All -> pAllo [arrowhead = none]
    pAllo -> CVC
    {rank = same; pAllo -> Excl[minlen=9]; rankdir = LR;}
    CVC -> pCVC [arrowhead = none]
    pCVC -> C3VC;
    pCVC -> C5VC;

    C3VC -> pC3VC [arrowhead = none];
    pC3VC -> C3VCB;
    pC3VC -> iC3VC [style = invis];
    pC3VC -> C3VCA;

    C5VC -> pC5VC [arrowhead = none]
    pC5VC -> C5VCV;
    pC5VC -> iC5VC [style = invis];
    pC5VC -> C5VCA;

    {rank = same; Analysis -> C3VCB -> iC3VC -> C3VCA -> C5VCV -> iC5VC -> C5VCA [style = invis]; rankdir = LR;};
}
[1]: nrow(cvc)
[2]: c(sum(cvc$isExcluded), excl_str)
[3]: sum(!cvc$isExcluded)
[4]: c(sum(cvc$Lumens == 3 & !cvc$isExcluded), sum(cvc$Lumens == 3 & !cvc$isExcluded & cvc$Manufacturer == 'Arrow'), sum(cvc$Lumens == 3 & !cvc$isExcluded & cvc$Manufacturer == 'Braun'))
[5]: c(sum(cvc$Lumens == 5 & !cvc$isExcluded), sum(cvc$Lumens == 5 & !cvc$isExcluded & cvc$Manufacturer == 'Arrow'), sum(cvc$Lumens == 5 & !cvc$isExcluded & cvc$Manufacturer == 'Vygon'))
"
grViz(graph)
```

```{r survplot, echo = FALSE}
#' Plot method for 'survfit' objects
#'
#' This is just a wrapper method around [`survival::plot.survfit()`] with
#' custom defaults.
#'
#' @param x `survfit` object.
#' @param main `character(1)`, plot title.
#' @param xlab `character(1)`, x-axis label.
#' @param ylab `character(1)`, y-axis label.
#' @param mark.time `logical(1)`, if `TRUE` censoring times are marked, see
#' [`survival::plot.survfit()`] for details.
#' @param conf.int `logical(1)`, if `TRUE` confidence interval is plotted, see
#' [`survival::plot.survfit()`] for details.
#' @param col `integer`/`character`, specifying colors for each curve.
#' @param times `integer`, vector of times to print on the x-axis.
#' @param \dots further arguments passed to [`survival::plot.survfit()`].
#'
#' @return a list with `x` and `y` containing the coordinates of the last point
#' of each curves.
#'
#' @seealso [`survival::plot.survfit()`]
#'
#' @import survival
#' @importFrom graphics axTicks axis text title
#' @importFrom grDevices palette.colors
#' @export
#' @examples
#' library("survival")
#' srvfit <- survfit(Surv(time, status) ~ x, data = aml)
#' plot_surv(srvfit)
plot_surv <- function(
    x,
    main = character(),
    xlab = "Time",
    ylab = "Overall survival probability",
    mark.time = TRUE,
    conf.int = FALSE,
    col = palette.colors(max(1L, length(x$strata))),
    times,
    ...) {

    if (!inherits(x, "survfit"))
        stop("'x' has to be an object of the 'survfit' class.")

    p <- plot(
        x,
        mark.time = mark.time, conf.int = conf.int, col = col,
        axes = FALSE, ann = FALSE,
        ...
    )
    if (missing(times))
        times <- axTicks(1L)
    title(main = main, adj = 0L)
    title(xlab = xlab, adj = 1L)
    title(ylab = ylab, adj = 1L)
    axis(1L, at = times, lwd.ticks = 0L, col = "#808080")
    axis(2L, lwd.ticks = 0L, col = "#808080")
    invisible(p)
}

#' Plot a table
#'
#' Plot a table on the current graphic device. Useful for risk tables.
#'
#' @param x `matrix`, it is transposed on the graphic device. The column names
#' correspond to the y labels and the row names to the x labels.
#' @param main `character(1)`, plot title.
#' @param xlab `character(1)`, x-axis label.
#' @param ylab `character(1)`, y-axis label.
#' @param at `numeric, where to plot the rows of `x`.
#' @param xlim `numeric(2)`, limits of the x-axis.
#' @param ylim `numeric(2)`, limits of the y-axis.
#' @param ylabels `logical(1)`, should the column names used to labels the
#' y-axis (default: `TRUE`)?
#' @param col `integer`/`character`, specifying the color for each y/column
#' label.
#' @param xaxis `logical(1)`, should the x-axis be plotted (default: `TRUE`)?
#' @param cex.xaxis `numeric(1)`, character expansion factor for the x-axis
#' labels, see [`par()`] for details.
#' @param cex.yaxis `numeric(1)`, character expansion factor for the y-axis
#' labels, see [`par()`] for details.
#' @param cex.text `numeric(1)`, character expansion factor for the cell content
#' labels, see [`par()`] for details.
#' @param \dots further arguments passed to [`plot.default()`].
#'
#' @return nothing, used for its side-effects (plotting).
#'
#' @export
#' @examples
#' m <- matrix(
#'     1:8, nrow = 4,
#'     dimnames = list(c(0, 30, 90, 365), LETTERS[1:2])
#' )
#' plot_table(m, main = "Cumulative number of events")
plot_table <- function(
    x,
    main = character(),
    xlab = character(),
    ylab = character(),
    at = seq_len(nrow(x)) - 1L,
    xlim = range(at),
    ylim = c(0L, ncol(x)),
    ylabels = TRUE,
    col = rep_len(1L, ncol(x)),
    xaxis = TRUE,
    cex.xaxis = 3/4,
    cex.yaxis = 1.25,
    cex.text = 1.5,
    ...
    ) {

    plot(
        NA,
        xlim = xlim,
        ylim = ylim,
        axes = FALSE, ann = FALSE,
        ...
    )
    title(main = main, adj = 0L)
    title(xlab = xlab, adj = 1L)
    title(ylab = ylab, adj = 1L)

    if (xaxis)
        axis(1L, at = at, cex.axis = cex.xaxis, lwd.ticks = 0L, col = "#808080")

    nc <- ncol(x)

    if (ylabels) {
        nm <- colnames(x)

        for (i in seq_len(nc)) {
            axis(
                side = 2L,
                at = (i - 1L), padj = -1L, las = 1L, labels = nm[i],
                col.axis = col[i], cex.axis = cex.yaxis, tick = FALSE
            )
        }
    }

    text(
        at, rep(seq_len(nc) - 1L, each = length(at)), pos = 3L,
        labels = x, cex = cex.text
    )
}


```

```{r survplotml3, echo = FALSE}
nms <- c("Arrow", "Braun")
old.par <- par(no.readonly = TRUE)
layout(matrix(1:3, nrow = 3), height = c(6, 1.5, 1.5))
plot_surv(
    ml3$srv,
    times = times,
    xmax = max(times),
    mark.time = TRUE,
    col = mcol[c("Arrow", "Braun")],
    main = "Thrombus free time of 3 lumens CVCs",
    xlab = "time [days]",
    conf.int = FALSE
)
legend(
    "topright",
    legend = nms,
    col = mcol[nms],
    lwd = 1, pch = 3, bty = "n"
)
par(mar = c(1.1, 7.1, 1.1, 2.1))
plot_table(
    .nrisk(ml3)[, 2:1], at = times, main = "Number at risk",
    xaxis = FALSE, cex.text = 1.0, col = mcol[nms]
)
par(mar = c(1.1, 7.1, 1.1, 2.1))
plot_table(
    .ncumevents(ml3)[, 2:1], at = times, main = "Cumulative number of events",
    xaxis = FALSE, cex.text = 1.0, col = mcol[nms]
)
```

```{r survplotml5, echo = FALSE}
nms <- c("Arrow", "Vygon")
old.par <- par(no.readonly = TRUE)
layout(matrix(1:3, nrow = 3), height = c(6, 1.5, 1.5))
plot_surv(
    ml5$srv,
    times = times,
    xmax = max(times),
    mark.time = TRUE,
    col = mcol[c("Arrow", "Vygon")],
    main = "Thrombus free time of 5 lumens CVCs",
    xlab = "time [days]",
    conf.int = TRUE
)
legend(
    "topright",
    legend = nms,
    col = mcol[nms],
    lwd = 1, pch = 3, bty = "n"
)
par(mar = c(1.1, 7.1, 1.1, 2.1))
plot_table(
    .nrisk(ml5)[, 2:1], at = times, main = "Number at risk",
    xaxis = FALSE, cex.text = 1.5, col = mcol[nms]
)
par(mar = c(1.1, 7.1, 1.1, 2.1))
plot_table(
    .ncumevents(ml5)[, 2:1], at = times, main = "Cumulative number of events",
    xaxis = FALSE, cex.text = 1.5, col = mcol[nms]
)
```

```{r survplotmlA, echo = FALSE}
nms <- c("3 Lumens", "5 Lumens")
plot_surv(
    mlA$srv,
    times = times,
    xmax = max(times),
    mark.time = TRUE,
    main = "Thrombus free time of Arrow CVCs",
    xlab = "time [days]",
    conf.int = TRUE
)
legend(
    "topright",
    legend = nms,
    lwd = 1, pch = 3, bty = "n"
)
```
