# Figures

## Flowchart

```{r knitr_setup_figures, include = FALSE}
is_docx_output <- function()
    isTRUE(knitr::opts_knit$get("rmarkdown.pandoc.to") == "docx")
ifelse_is_docx <- function(docx, others) {
    if (is_docx_output())
        docx
    else
        others
}
```

```{r knitr_setup_figures_word, eval = is_docx_output(), include = FALSE}
knitr::opts_chunk$set(
    dpi = 1200,
    units = "in",
    res = 1200,
    dev.args = list(
        pdf = list(
            family = "ArialMT",
            pointsize = 18
        ),
        tiff = list(
            family = "ArialMT",
            pointsize = 18,
            compression = "zip"
        )
    )
)
```

```{r consort-flowchart, echo = FALSE, warning = FALSE, dev = ifelse_is_docx(c("tiff", "pdf"), "png"), fig.width = 14, fig.height = 7, fig.cap = "CONSORT diagram: the flowchart shows the inclusion and exclusion criteria. CVC, central venous catheter; DOAC, direct oral anticoagulants; FV, femoral vein; SCV, subclavian vein."}
library("consort")

.txt <- function(label, n)paste0(label, "\n (n = ", n, ")")
narms <- table(cvc$ManLu[!cvc$isExcluded])
narms <- narms[narms > 0]
arms <- .manlu2txt(names(narms))
excl <- table(cvc$ExclusionReason)
eord <- c(
    grep("Not the first", names(excl)),
    grep("Site", names(excl)),
    grep("Not inserted ", names(excl)),
    grep("Lumen", names(excl)),
    grep("Missing LOT", names(excl)),
    grep("DOAC", names(excl))
)
eord <- c(seq_len(length(excl))[eord], seq_len(length(excl))[-eord])
excl <- excl[eord]

excl <- paste0(
    "Excluded (n = ", sum(excl), ")",
    paste0("\n- ", names(excl), " (n = ", excl, ")", collapse = "")
)

cnsrt <-
    add_box(txt = .txt("Screened CVCs", nrow(cvc))) |>
    add_side_box(txt = excl) |>
    add_box(txt = .txt("Eligible CVCs", sum(!cvc$isExcluded))) |>
    add_split(txt = .txt(arms, narms)) |>
    add_label_box(txt = c(
        "1" = "Enrollment",
        "2" = "Allocation",
        "3" = "Analysis")
    )
plot(cnsrt)
```

## Survival plots

```{r survivalplothelper, include = FALSE}
## taken from ameld

#' Plot method for 'survfit' objects
#'
#' This is just a wrapper method around [`survival::plot.survfit()`] with
#' custom defaults.
#'
#' @param x `survfit` object.
#' @param main `character(1)`, plot title.
#' @param xlab `character(1)`, x-axis label.
#' @param ylab `character(1)`, y-axis label.
#' @param mark.time `logical(1)`, if `TRUE` censoring times are marked, see
#' [`survival::plot.survfit()`] for details.
#' @param conf.int `logical(1)`, if `TRUE` confidence interval is plotted, see
#' [`survival::plot.survfit()`] for details.
#' @param col `integer`/`character`, specifying colors for each curve.
#' @param times `integer`, vector of times to print on the x-axis.
#' @param \dots further arguments passed to [`survival::plot.survfit()`].
#'
#' @return a list with `x` and `y` containing the coordinates of the last point
#' of each curves.
#'
#' @seealso [`survival::plot.survfit()`]
#'
#' @import survival
#' @importFrom graphics axTicks axis text title
#' @importFrom grDevices palette.colors
#' @export
#' @examples
#' library("survival")
#' srvfit <- survfit(Surv(time, status) ~ x, data = aml)
#' plot_surv(srvfit)
plot_surv <- function(
    x,
    main = character(),
    xlab = "Time",
    ylab = "Overall survival probability",
    mark.time = TRUE,
    conf.int = FALSE,
    col = palette.colors(max(1L, length(x$strata))),
    times,
    ...) {
    if (!inherits(x, "survfit"))
        stop("'x' has to be an object of the 'survfit' class.")
    p <- plot(
        x,
        mark.time = mark.time, conf.int = conf.int, col = col,
        axes = FALSE, ann = FALSE,
        ...
    )
    if (missing(times))
        times <- axTicks(1L)
    title(main = main, adj = 0L)
    title(xlab = xlab, adj = 1L)
    title(ylab = ylab, adj = 1L)
    axis(1L, at = times, lwd.ticks = 0L, col = "#808080")
    axis(2L, lwd.ticks = 0L, col = "#808080")
    invisible(p)
}

#' Plot a table
#'
#' Plot a table on the current graphic device. Useful for risk tables.
#'
#' @param x `matrix`, it is transposed on the graphic device. The column names
#' correspond to the y labels and the row names to the x labels.
#' @param main `character(1)`, plot title.
#' @param xlab `character(1)`, x-axis label.
#' @param ylab `character(1)`, y-axis label.
#' @param at `numeric, where to plot the rows of `x`.
#' @param xlim `numeric(2)`, limits of the x-axis.
#' @param ylim `numeric(2)`, limits of the y-axis.
#' @param ylabels `logical(1)`, should the column names used to labels the
#' y-axis (default: `TRUE`)?
#' @param col `integer`/`character`, specifying the color for each y/column
#' label.
#' @param xaxis `logical(1)`, should the x-axis be plotted (default: `TRUE`)?
#' @param cex.xaxis `numeric(1)`, character expansion factor for the x-axis
#' labels, see [`par()`] for details.
#' @param cex.yaxis `numeric(1)`, character expansion factor for the y-axis
#' labels, see [`par()`] for details.
#' @param cex.text `numeric(1)`, character expansion factor for the cell content
#' labels, see [`par()`] for details.
#' @param \dots further arguments passed to [`plot.default()`].
#'
#' @return nothing, used for its side-effects (plotting).
#'
#' @export
#' @examples
#' m <- matrix(
#'     1:8, nrow = 4,
#'     dimnames = list(c(0, 30, 90, 365), LETTERS[1:2])
#' )
#' plot_table(m, main = "Cumulative number of events")
plot_table <- function(
    x,
    main = character(),
    xlab = character(),
    ylab = character(),
    at = seq_len(nrow(x)) - 1L,
    xlim = range(at),
    ylim = c(0L, ncol(x)),
    ylabels = TRUE,
    col = rep_len(1L, ncol(x)),
    xaxis = TRUE,
    cex.xaxis = 3/4,
    cex.yaxis = 1.25,
    cex.text = 1.5,
    ...
    ) {
    plot(
        NA,
        xlim = xlim,
        ylim = ylim,
        axes = FALSE, ann = FALSE,
        ...
    )
    title(main = main, adj = 0L)
    title(xlab = xlab, adj = 1L)
    title(ylab = ylab, adj = 1L)
    if (xaxis)
        axis(1L, at = at, cex.axis = cex.xaxis, lwd.ticks = 0L, col = "#808080")
    nc <- ncol(x)
    if (ylabels) {
        nm <- colnames(x)
        for (i in seq_len(nc)) {
            axis(
                side = 2L,
                at = (i - 1L), padj = -1L, las = 1L, labels = nm[i],
                col.axis = col[i], cex.axis = cex.yaxis, tick = FALSE
            )
        }
    }
    text(
        at, rep(seq_len(nc) - 1L, each = length(at)), pos = 3L,
        labels = x, cex = cex.text
    )
}
```

```{r survplot, echo = FALSE, dev = ifelse_is_docx(c("tiff", "pdf"), "png"), fig.width = 12, fig.height = 8, fig.cap = "Survival plot showing CRT-free time for all analysed central venous catheters. Confidence intervals overlap and have not been drawn for ease of visualization."}
old.par <- par(no.readonly = TRUE)
xlim <- c(0.8, max(times))
mar <- c(0.1, 10.1, 1.1, 2.1)
nms <- .manlu2txt(gsub("ManLu=", "", names(m$svf$strata)))
col <- mcol[sapply(strsplit(nms, "/", fixed = TRUE), "[[", 1)]
lty <- llty[sapply(strsplit(nms, "/", fixed = TRUE), "[[", 2)]
names(col) <- names(lty) <- nms

layout(matrix(1:3, nrow = 3), height = c(6, 1.5, 1.5))
par(mar = c(5.1, mar[-1]), bg = "white")
plot_surv(
    m$svf,
    times = times,
    xlim = xlim,
    ylim = c(0, 1),
    mark.time = FALSE,
    col = col,
    lty = lty,
    lwd = 2,
    main = "Thrombus free time of CVCs",
    xlab = "time [days]"
)
#points(
#    median(m$svf), rep(0.5, length(nms)),
#    col = "black", lty = "dotted", type = "h"
#)
legend(
    "topright",
    legend = nms,
    col = col, lty = lty,
    lwd = 1, seg.len = 3, bty = "n"
)

.revcol <- function(x)x[, rev(seq_len(ncol(x)))]
nr <- drop(.nrisk(m$svf))
nce <- drop(.ncumevents(m$svf))
colnames(nr) <- colnames(nce) <- nms
nr <- .revcol(nr)
nce <- .revcol(nce)

par(mar = mar)
plot_table(
    nr, at = times, xlim = xlim,
    main = "Number at risk",
    xaxis = FALSE, cex.text = 1.1, col = col[colnames(nr)]
)
par(mar = mar)
plot_table(
    nce, at = times, xlim = xlim,
    main = "Cumulative number of events",
    xaxis = FALSE, cex.text = 1.1, col = col[colnames(nce)]
)
```

## Regression

```{r ggforest-mod, include = FALSE}
## taken from survminer::ggforest, added rename argument to change labels
.ggforest <- function(model, data = NULL,
  main = "Hazard ratio of CRT", cpositions=c(0.02, 0.22, 0.4),
  labpos = c(0.5, 2),
  fontsize = 0.7, refLabel = "reference", noDigits=2,
  rename = NULL) {
  conf.high <- conf.low <- estimate <- NULL
  stopifnot(inherits(model, "coxph"))

  # get data and variables/terms from cox model
  data  <- survminer:::.get_data(model, data = data)
  terms <- attr(model$terms, "dataClasses")[-1]
# removed as requested in #388
#  terms <- terms[intersect(names(terms),
#    gsub(rownames(anova(model))[-1], pattern = "`", replacement = ""))]

  # use broom to get some required statistics
  coef <- as.data.frame(broom::tidy(model, conf.int = TRUE))
  gmodel <- broom::glance(model)

  # extract statistics for every variable
  allTerms <- lapply(seq_along(terms), function(i){
    var <- names(terms)[i]
    if (terms[i] %in% c("factor", "character")) {
      adf <- as.data.frame(table(data[, var]))
      cbind(var = var, adf, pos = 1:nrow(adf))
    }
    else if (terms[i] == "numeric") {
      data.frame(var = var, Var1 = "", Freq = nrow(data),
                 pos = 1)
    }
    else {
      vars = grep(paste0("^", var, "*."), coef$term, value=TRUE)
      data.frame(var = vars, Var1 = "", Freq = nrow(data),
                 pos = seq_along(vars))
    }
  })
  allTermsDF <- do.call(rbind, allTerms)
  colnames(allTermsDF) <- c("var", "level", "N", "pos")
  inds <- apply(allTermsDF[,1:2], 1, paste0, collapse="")

  # use broom again to get remaining required statistics
  rownames(coef) <- gsub(coef$term, pattern = "`", replacement = "")
  toShow <- cbind(allTermsDF, coef[inds,])[,c("var", "level", "N", "p.value", "estimate", "conf.low", "conf.high", "pos")]
  toShowExp <- toShow[,5:7]
  toShowExp[is.na(toShowExp)] <- 0
  toShowExp <- format(exp(toShowExp), digits=noDigits)
  toShowExpClean <- data.frame(toShow,
    pvalue = signif(toShow[,4],noDigits+1),
    toShowExp)
  toShowExpClean$stars <- paste0(round(toShowExpClean$p.value, noDigits+1), " ",
    ifelse(toShowExpClean$p.value < 0.05, "*",""),
    ifelse(toShowExpClean$p.value < 0.01, "*",""),
    ifelse(toShowExpClean$p.value < 0.001, "*",""))
  toShowExpClean$ci <- paste0("(",toShowExpClean[,"conf.low.1"]," - ",toShowExpClean[,"conf.high.1"],")")
  toShowExpClean$estimate.1[is.na(toShowExpClean$estimate)] = refLabel
  toShowExpClean$stars[which(toShowExpClean$p.value < 0.001)] = "<0.001 ***"
  toShowExpClean$stars[is.na(toShowExpClean$estimate)] = ""
  toShowExpClean$ci[is.na(toShowExpClean$estimate)] = ""
  toShowExpClean$estimate[is.na(toShowExpClean$estimate)] = 0
  toShowExpClean$var = as.character(toShowExpClean$var)
  toShowExpClean$var[duplicated(toShowExpClean$var)] = ""
  # make label strings:
  toShowExpClean$N <- paste0("(N=",toShowExpClean$N,")")

  #flip order
  toShowExpClean <- toShowExpClean[nrow(toShowExpClean):1, ]

  ## added the follow lines
  if (!is.null(rename))
    for (i in seq_along(rename))
        toShowExpClean$var[toShowExpClean$var == names(rename)[i]] <- rename[i]

  rangeb <- range(toShowExpClean$conf.low, toShowExpClean$conf.high, na.rm = TRUE)
  breaks <- axisTicks(rangeb/2, log = TRUE, nint = 7)
  rangeplot <- rangeb
  # make plot twice as wide as needed to create space for annotations
  rangeplot[1] <- rangeplot[1] - diff(rangeb)
  # increase white space on right for p-vals:
  rangeplot[2] <- rangeplot[2] + .15 * diff(rangeb)

  width <- diff(rangeplot)
  # y-coordinates for labels:
  y_variable <- rangeplot[1] +  cpositions[1] * width
  y_nlevel <- rangeplot[1]  +  cpositions[2] * width
  y_cistring <- rangeplot[1]  +  cpositions[3] * width
  y_stars <- rangeb[2]
  x_annotate <- seq_len(nrow(toShowExpClean))

  # geom_text fontsize is in mm (https://github.com/tidyverse/ggplot2/issues/1828)
  annot_size_mm <- fontsize *
      as.numeric(grid::convertX(unit(theme_get()$text$size, "pt"), "mm"))

  p <- ggplot(toShowExpClean, aes(seq_along(var), exp(estimate))) +
    geom_rect(aes(xmin = seq_along(var) - .5, xmax = seq_along(var) + .5,
      ymin = exp(rangeplot[1]), ymax = exp(rangeplot[2]),
      fill = ordered(seq_along(var) %% 2 + 1))) +
    scale_fill_manual(values = c("#FFFFFF33", "#00000033"), guide = "none") +
    geom_point(pch = 15, size = 4) +
    geom_errorbar(aes(ymin = exp(conf.low), ymax = exp(conf.high)), width = 0.15) +
    geom_hline(yintercept = 1, linetype = 3) +
    coord_flip(ylim = exp(rangeplot)) +
    ggtitle(main) +
    scale_y_log10(
      name = "",
      labels = sprintf("%g", breaks),
      expand = c(0.02, 0.02),
      breaks = breaks) +
    theme_light() +
    theme(panel.grid.minor.y = element_blank(),
      panel.grid.minor.x = element_blank(),
      panel.grid.major.y = element_blank(),
      legend.position = "none",
      panel.border=element_blank(),
      axis.title.y=element_blank(),
      axis.text.y=element_blank(),
      axis.ticks.y=element_blank(),
      plot.title = element_text(hjust = 0.5)) +
    xlab("") +
    annotate(geom = "text", x = x_annotate, y = exp(y_variable),
      label = toShowExpClean$var, fontface = "bold", hjust = 0,
      size = annot_size_mm) +
    annotate(geom = "text", x = x_annotate, y = exp(y_nlevel), hjust = 0,
      label = toShowExpClean$level, vjust = -0.1, size = annot_size_mm) +
    annotate(geom = "text", x = x_annotate, y = exp(y_nlevel),
      label = toShowExpClean$N, fontface = "italic", hjust = 0,
      vjust = ifelse(toShowExpClean$level == "", .5, 1.1),
      size = annot_size_mm) +
    annotate(geom = "text", x = x_annotate, y = exp(y_cistring),
      label = toShowExpClean$estimate.1, size = annot_size_mm,
      vjust = ifelse(toShowExpClean$estimate.1 == "reference", .5, -0.1)) +
    annotate(geom = "text", x = x_annotate, y = exp(y_cistring),
      label = toShowExpClean$ci, size = annot_size_mm,
      vjust = 1.1,  fontface = "italic") +
    annotate(geom = "text", x = x_annotate, y = exp(y_stars),
      label = toShowExpClean$stars, size = annot_size_mm,
      hjust = -0.2,  fontface = "italic") +
    annotate(geom = "text", x = 0.5, y = exp(y_variable),
      label = paste0("# Events: ", gmodel$nevent, "; Global p-value (Log-Rank): ",
        format.pval(gmodel$p.value.log, eps = ".001"), " \nAIC: ", round(gmodel$AIC,2),
        "; Concordance Index: ", round(gmodel$concordance,2)),
      size = annot_size_mm, hjust = 0, vjust = 1.2,  fontface = "italic") +
    annotate(geom = "text", x = 0, y = labpos[1], label = "Favours CRT-free") +
    annotate(geom = "text", x = 0, y = labpos[2], label = "Favours CRT")
  # switch off clipping for p-vals, bottom annotation:
  gt <- ggplot_gtable(ggplot_build(p))
  gt$layout$clip[gt$layout$name == "panel"] <- "off"
  # grid.draw(gt)
  # invisible(p)
  ggpubr::as_ggplot(gt)
}
```

```{r forestplot, echo = FALSE, dev = ifelse_is_docx(c("tiff", "pdf"), "png"), fig.width = 12, fig.height = 8, fig.cap = "Hazard ratios of CRT adjusted for different covariates. CRT, catheter-related thrombosis; CVC, central venous catheter; DVT, deep vein thrombosis; LMWH, low-molecular-weight heparins; UFH, unfractionated heparin; WBC1, white blood cell count on day one."}
.ggforest(
    rgcx, data = rd,
    rename = rgcx.nms
)
```
