(specifications->manifest
  '("bash-minimal"
    "coreutils"
    "nss-certs"
    "r-minimal"
    "r-beeswarm"
    "r-bookdown"
    "r-codetools"
    "r-consort"
    "r-gtsummary"
    "r-rprojroot"
    "r-survival"
    "r-survminer"
    "r-viridislite"))
