(specifications->manifest
  '("r-minimal"
    "r-beeswarm"
    "r-bibtex"
    "r-bookdown"
    "r-consort"
    "r-gtsummary"
    "r-rprojroot"
    "r-survival"
    "r-survminer"
    "r-viridislite"))
